#! /usr/bin/env python3

"""
Packet Commands
"""
COMMAND_CPU_WRITE = 1
COMMAND_CPU_READ = 2
COMMAND_DAQ_WRITE = 3
COMMAND_DAQ_READ = 4

"""
RAM ADDRESSES
"""
RAM0_BASE_ADDRESS = 0x90000000
RAM1_BASE_ADDRESS = 0x90002000
RAM2_BASE_ADDRESS = 0x90004000
RAM3_BASE_ADDRESS = 0x90006000

"""
GPIO
"""
GPIO_BASE_ADDRESS = 0x40000000

GPIO_R_IN = GPIO_BASE_ADDRESS + 0
GPIO_R_OUT = GPIO_BASE_ADDRESS + 4
GPIO_R_OE = GPIO_BASE_ADDRESS + 8
GPIO_R_INTE = GPIO_BASE_ADDRESS + 12
GPIO_R_PTRIG = GPIO_BASE_ADDRESS + 16
GPIO_R_AUX = GPIO_BASE_ADDRESS + 20
GPIO_R_CTRL = GPIO_BASE_ADDRESS + 24
GPIO_F_CTRL_INTE = 0
GPIO_B_CTRL_INTE = (1 << GPIO_F_CTRL_INTE)
GPIO_F_CTRL_INTS = 1
GPIO_B_CTRL_INTS = (1 << GPIO_F_CTRL_INTS)
GPIO_R_INTS = GPIO_BASE_ADDRESS + 28
GPIO_R_ECLK = GPIO_BASE_ADDRESS + 32
GPIO_R_NEC = GPIO_BASE_ADDRESS + 32

"""
SYSCON
"""
SYSCON_BASE_ADDRESS = 0x40001000
SYSCON_R_IDENTIFICATION = SYSCON_BASE_ADDRESS + 0
SYSCON_R_STATUS = SYSCON_BASE_ADDRESS + 4
F_SYSCON_STATUS_LOCKED = 0
B_SYSCON_STATUS_LOCKED = (1 << F_SYSCON_STATUS_LOCKED)
SYSCON_R_CONTROL = SYSCON_BASE_ADDRESS + 8

"""
DSP SLAVE
"""
WB_DSP_SLAVE_BASE_ADDRESS = (0x70000000)
WB_DSP_SLAVE_INPUT0 = WB_DSP_SLAVE_BASE_ADDRESS + 0
B_DSP_EQUATION_NONE = 0x00
B_DSP_EQUATION_SUM = 0x01
B_DSP_EQUATION_MULTIPLY = 0x02
B_DSP_EQUATION_DTREE = 0x03
B_DSP_SLAVE_DATA_SIGNED = (1 << 10)
B_DSP_SLAVE_ENABLE_MAC = (1 << 11)
B_DSP_SLAVE_SCALAR_MULTIPLY = (1 << 12)
B_DSP_SLAVE_EQUATION_START = (1 << 31)


WB_DSP_SLAVE_INPUT1 = WB_DSP_SLAVE_BASE_ADDRESS + 4
WB_DSP_SLAVE_INPUT2 = WB_DSP_SLAVE_BASE_ADDRESS + 8
WB_DSP_SLAVE_INPUT3 = WB_DSP_SLAVE_BASE_ADDRESS + 0x0C
WB_DSP_SLAVE_INPUT4 = WB_DSP_SLAVE_BASE_ADDRESS + 0x10
WB_DSP_SLAVE_OUTPUT0 = WB_DSP_SLAVE_BASE_ADDRESS + 0x14
WB_DSP_SLAVE_OUTPUT1 = WB_DSP_SLAVE_BASE_ADDRESS + 0x18
WB_DSP_SLAVE_OUTPUT2 = WB_DSP_SLAVE_BASE_ADDRESS + 0x1C
WB_DSP_SLAVE_OUTPUT3 = WB_DSP_SLAVE_BASE_ADDRESS + 0x20
WB_DSP_SLAVE_OUTPUT4 = WB_DSP_SLAVE_BASE_ADDRESS + 0x24

B_CONTROL_DATA_SIZE_WORD = 0x00
B_CONTROL_DATA_SIZE_HWORD = 0x01
B_CONTROL_DATA_SIZE_BYTE = 0x02
B_CONTROL_DATA_SIZE_UNDEFINED = 0x03
